apiVersion: v1
kind: Namespace
metadata:
  name: sasche
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sasche-cr
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - delete
      - get
      - list
      - watch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sasche-sa
  namespace: sasche
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sasche-crb
  namespace: sasche
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sasche-cr
subjects:
  - kind: ServiceAccount
    name: sasche-sa
    namespace: sasche
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sasche
  namespace: sasche
  labels:
    app: sasche
spec:
  selector:
    matchLabels:
      app: sasche
  template:
    metadata:
      labels:
        app: sasche
    spec:
      serviceAccountName: sasche-sa
      containers:
        - name: sasche
          image: singaauto/singa_auto_nodegpumonitor:dev
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: MODE
              value: "MaxFreeMemory"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30